-- keep clangd, disable only its formatting for this buffer
-- vim.api.nvim_create_autocmd("LspAttach", {
-- 	buffer = 0,
-- 	callback = function(args)
-- 		local client = vim.lsp.get_client_by_id(args.data.client_id)
-- 		if client and client.name == "clangd" then
-- 			client.server_capabilities.documentFormattingProvider = false
-- 			client.server_capabilities.documentRangeFormattingProvider = false
-- 			vim.notify("clangd formatting disabled (buffer-local)")
-- 		end
-- 	end,
-- })
